require("core.lazy")
require("core.opts")
require("core.keys")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.auto_complete")
require("plugins.status_line")
require("plugins.buffer_line")
require("plugins.file_tree")
require("plugins.indent_lines")
require("mason").setup()
require("gitsigns").setup()
require("nvim-autopairs").setup()
--require("telescope").setup {}
