pcall(require, "luarocks.loader")
collectgarbage("setpause", 110)
collectgarbage("setstepmul", 1000)

require("core.error")
require("core.theme")
require("core.tags")
require("ui")
require("core.rules")
require("core.binds")
