local T = {}

function T.set_colors(p)
	local theme = {
		-- base highlights
		Normal = { fg = p.fg, bg = p.bg },
		NormalNC = { fg = p.fg, bg = p.bg },
		SignColumn = { fg = p.bg },
		FoldColumn = { fg = p.fg_alt },
		VertSplit = { fg = p.bg_alt },
		WinSeparator = { fg = p.bg_alt },
		Folded = { fg = p.fg },
		EndOfBuffer = { fg = p.bg_alt },
		ColorColumn = { bg = p.bg_alt },
		Conceal = { fg = p.fg_alt },
		QuickFixLine = { bg = p.bg },
		Terminal = { fg = p.fg, bg = p.bg },
		Directory = { fg = p.blue },
		ErrorMsg = { fg = p.red },
		WarningMsg = { fg = p.yellow },
		ModeMsg = { fg = p.fg },
		MoreMsg = { fg = p.fg },
		MsgArea = { fg = p.fg, bg = p.bg },
		MsgSeparator = { fg = p.bg_alt, bg = p.bg },
		Title = { fg = p.cyan },
		Question = { fg = p.cyan },
		IncSearch = { fg = p.bg, bg = p.orange },
		Search = { fg = p.bg, bg = p.yellow },
		Visual = { fg = p.bg, bg = p.cyan },
		Substitute = { fg = p.bg, bg = p.magenta },
		VisualNOS = { fg = p.bg, bg = p.fg },
		Cursor = { fg = p.fg, bg = p.fg },
		CursorColumn = { bg = p.bg_alt },
		CursorIM = { fg = p.fg, bg = p.fg },
		CursorLine = { bg = p.bg_alt },
		CursorLineNr = { fg = p.cyan },
		lCursor = { fg = p.fg, bg = p.fg },
		LineNr = { fg = p.fg_alt },
		TermCursor = { fg = p.fg, bg = p.fg },
		TermCursorNC = { fg = p.fg, bg = p.fg },
		DiffAdd = { fg = p.green },
		DiffChange = { fg = p.yellow },
		DiffDelete = { fg = p.red },
		DiffText = { fg = p.fg },
		MatchParen = { fg = p.yellow, bg = p.bg_urgent },
		NonText = { fg = p.fg_alt },
		SpecialKey = { fg = p.fg_alt },
		Whitespace = { fg = p.bg_alt },
		Pmenu = { fg = p.fg, bg = p.bg_alt },
		PmenuSbar = { bg = p.bg_urgent },
		PmenuSel = { fg = p.bg, bg = p.cyan },
		PmenuThumb = { bg = p.cyan },
		WildMenu = { fg = p.fg, bg = p.bg_alt },
		NormalFloat = { fg = p.fg, bg = p.bg_alt },
		TabLine = { fg = p.fg, bg = p.bg },
		TabLineFill = { fg = p.fg, bg = p.bg },
		TabLineSel = { fg = p.cyan, bg = p.bg },
		StatusLine = { fg = p.fg, bg = p.bg },
		StatusLineNC = { bg = p.bg, fg = p.bg },
		SpellBad = { fg = p.red },
		SpellCap = { fg = p.blue },
		SpellLocal = { fg = p.cyan },
		SpellRare = { fg = p.magenta },
		FloatShadow = { fg = p.none, bg = p.none },
		FloatShadowThrough = { fg = p.none, bg = p.none },

		-- syntax
		Boolean = { fg = p.orange },
		Character = { fg = p.orange },
		Conditional = { fg = p.magenta },
		Constant = { fg = p.orange },
		Debug = { fg = p.blue },
		Define = { fg = p.red },
		Error = { fg = p.red },
		Exception = { fg = p.magenta },
		Float = { fg = p.yellow },
		FloatBorder = { fg = p.fg_alt },
		Function = { fg = p.blue },
		Include = { fg = p.red },
		Keyword = { fg = p.red },
		Label = { fg = p.blue },
		Macro = { fg = p.blue },
		Number = { fg = p.yellow },
		Operator = { fg = p.red },
		PreCondit = { fg = p.blue },
		PreProc = { fg = p.blue },
		Repeat = { fg = p.magenta },
		Special = { fg = p.blue },
		SpecialChar = { fg = p.orange },
		Statement = { fg = p.blue },
		Storage = { fg = p.blue },
		StorageClass = { fg = p.blue },
		String = { fg = p.green },
		Structure = { fg = p.blue },
		Tag = { fg = p.red },
		Type = { fg = p.blue },
		Typedef = { fg = p.blue },
		Variable = { fg = p.blue },
		Comment = { fg = p.fg_alt },
		SpecialComment = { fg = p.fg_alt },
		Todo = { fg = p.fg_alt },
		Delimiter = { fg = p.fg },
		Identifier = { fg = p.fg },
		Ignore = { fg = p.fg },
		Underlined = { underline = true },

		-- bufferline.nvim: https://github.com/akinsho/bufferline.nvim
		BufferLineFill = { fg = p.bg, bg = p.bg },
		BufferLineIndicatorSelected = { fg = p.cyan },

		-- Diagnostic
		DiagnosticError = { fg = p.red },
		DiagnosticHint = { fg = p.cyan },
		DiagnosticInfo = { fg = p.blue },
		DiagnosticWarn = { fg = p.yellow },
		DiagnosticOk = { fg = p.green },

		-- diff
		diffAdded = { fg = p.blue },
		diffChanged = { fg = p.yellow },
		diffFile = { fg = p.fg },
		diffIndexLine = { fg = p.fg },
		diffLine = { fg = p.fg },
		diffNewFile = { fg = p.magenta },
		diffOldFile = { fg = p.orange },
		diffRemoved = { fg = p.red },

		-- gitsigns: https://github.com/lewis6991/gitsigns.nvim
		GitSignsAdd = { fg = p.green },
		GitSignsChange = { fg = p.yellow },
		GitSignsDelete = { fg = p.red },

		-- indent-blankline.nvim: https://github.com/lukas-reineke/indent-blankline.nvim
		IndentBlanklineChar = { fg = p.bg_alt },

		-- nvim-tree.lua: https://github.com/nvim-tree/nvim-tree.lua
		NvimTreeEmptyFolderName = { fg = p.fg_alt },
		NvimTreeEndOfBuffer = { fg = p.fg, bg = p.bg },
		NvimTreeEndOfBufferNC = { fg = p.fg, bg = p.bg },
		NvimTreeFolderIcon = { fg = p.fg, bg = p.bg },
		NvimTreeFolderName = { fg = p.fg },
		NvimTreeGitDeleted = { fg = p.red },
		NvimTreeGitDirty = { fg = p.red },
		NvimTreeGitNew = { fg = p.blue },
		NvimTreeImageFile = { fg = p.fg_alt },
		NvimTreeIndentMarker = { fg = p.cyan },
		NvimTreeNormal = { fg = p.fg, bg = p.bg },
		NvimTreeNormalNC = { fg = p.fg, bg = p.bg },
		NvimTreeOpenedFolderName = { fg = p.cyan },
		NvimTreeRootFolder = { fg = p.fg_alt },
		NvimTreeSpecialFile = { fg = p.red },
		NvimTreeStatusLineNC = { bg = p.bg, fg = p.bg },
		NvimTreeSymlink = { fg = p.blue },
		NvimTreeVertSplit = { fg = p.fg_alt, bg = p.bg },
		NvimTreeWindowPicker = { fg = p.red, bg = p.bg_alt },

		-- nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter
		["@attribute"] = { fg = p.blue },
		["@boolean"] = { fg = p.orange },
		["@character"] = { fg = p.orange },
		["@comment"] = { fg = p.fg_alt },
		["@conditional"] = { fg = p.magenta },
		["@constant"] = { fg = p.fg },
		["@constant.builtin"] = { fg = p.orange },
		["@constant.macro"] = { fg = p.orange },
		["@constructor"] = { fg = p.blue },
		["@exception"] = { fg = p.magenta },
		["@field"] = { fg = p.cyan },
		["@float"] = { fg = p.yellow },
		["@function"] = { fg = p.blue },
		["@function.builtin"] = { fg = p.blue },
		["@function.macro"] = { fg = p.blue },
		["@include"] = { fg = p.red },
		["@keyword"] = { fg = p.red },
		["@keyword.conditional"] = { fg = p.magenta },
		["@keyword.function"] = { fg = p.red },
		["@keyword.operator"] = { fg = p.red },
		["@keyword.return"] = { fg = p.red },
		["@label"] = { fg = p.cyan },
		["@method"] = { fg = p.blue },
		["@namespace"] = { fg = p.cyan },
		["@number"] = { fg = p.yellow },
		["@operator"] = { fg = p.red },
		["@parameter"] = { fg = p.yellow },
		["@parameter.reference"] = { fg = p.yellow },
		["@property"] = { fg = p.cyan },
		["@punctuation.bracket"] = { fg = p.fg },
		["@punctuation.delimiter"] = { fg = p.fg },
		["@punctuation.special"] = { fg = p.fg },
		["@repeat"] = { fg = p.magenta },
		["@string"] = { fg = p.green },
		["@string.escape"] = { fg = p.orange },
		["@string.regex"] = { fg = p.orange },
		["@string.special"] = { fg = p.orange },
		["@symbol"] = { fg = p.red },
		["@tag"] = { fg = p.red },
		["@tag.attribute"] = { fg = p.yellow },
		["@tag.delimiter"] = { fg = p.blue },
		["@type"] = { fg = p.blue },
		["@type.builtin"] = { fg = p.blue },
		["@variable"] = { fg = p.fg },
		["@variable.builtin"] = { fg = p.fg },
		["@text"] = { fg = p.fg },

		--[[
		["@annotation"] = { link = "TSAnnotation" },
		["@attribute"] = { link = "TSAttribute" },
		["@boolean"] = { link = "TSBoolean" },
		["@boolean.yaml"] = { link = "yamlTSBoolean" },
		["@character"] = { link = "TSCharacter" },
		["@character.special"] = { link = "TSCharacterSpecial" },
		["@comment"] = { link = "TSComment" },
		["@comment.error"] = { link = "TSDanger" }, -- Used to be @text.danger
		["@comment.note"] = { link = "TSNote" },
		["@comment.todo"] = { link = "TSTodo" },
		["@comment.warning"] = { link = "TSWarning" },
		["@conceal"] = { link = "Grey" },
		["@conditional"] = { link = "TSConditional" },
		["@constant"] = { link = "TSConstant" },
		["@constant.builtin"] = { link = "TSConstBuiltin" },
		["@constant.builtin.go"] = { link = "goTSConstBuiltin" },
		["@constant.builtin.yaml"] = { link = "yamlTSConstBuiltin" },
		["@constant.macro"] = { link = "TSConstMacro" },
		["@constant.regex"] = { link = "TSConstBuiltin" },
		["@constructor"] = { link = "TSConstructor" },
		["@constructor.lua"] = { link = "luaTSConstructor" },
		["@constructor.tsx"] = { link = "tsxTSConstructor" },
		["@debug"] = { link = "TSDebug" },
		["@define"] = { link = "TSDefine" },
		["@diff.delta"] = { link = "diffChanged" },
		["@diff.minus"] = { link = "diffRemoved" },
		["@diff.plus"] = { link = "diffAdded" },
		["@error"] = { link = "TSError" }, -- This has been removed from nvim-treesitter
		["@exception"] = { link = "TSException" },
		["@field"] = { link = "TSField" },
		["@field.yaml"] = { link = "yamlTSField" },
		["@float"] = { link = "TSFloat" },
		["@function"] = { link = "TSFunction" },
		["@function.builtin"] = { link = "TSFuncBuiltin" },
		["@function.call"] = { link = "TSFunctionCall" },
		["@function.macro"] = { link = "TSFuncMacro" },
		["@function.method"] = { link = "TSMethod" },
		["@function.method.call"] = { link = "TSMethodCall" },
		["@include"] = { link = "TSInclude" },
		["@include.go"] = { link = "goTSInclude" },
		["@include.javascript"] = { link = "javascriptTSInclude" },
		["@include.typescript"] = { link = "typescriptTSInclude" },
		["@keyword"] = { link = "TSKeyword" },
		["@keyword.conditional"] = { link = "TSConditional" },
		["@keyword.debug"] = { link = "TSDebug" },
		["@keyword.directive"] = { link = "TSPreProc" },
		["@keyword.directive.define"] = { link = "TSDefine" },
		["@keyword.exception"] = { link = "TSException" },
		["@keyword.function"] = { link = "TSKeywordFunction" },
		["@keyword.import"] = { link = "TSInclude" },
		["@keyword.import.go"] = { link = "goTSInclude" },
		["@keyword.import.javascript"] = { link = "javascriptTSInclude" },
		["@keyword.import.typescript"] = { link = "typescriptTSInclude" },
		["@keyword.operator"] = { link = "TSKeywordOperator" },
		["@keyword.repeat"] = { link = "TSRepeat" },
		["@keyword.return"] = { link = "TSKeywordReturn" },
		["@keyword.storage"] = { link = "TSStorageClass" },
		["@label"] = { link = "TSLabel" },
		["@label.json"] = { link = "jsonTSLabel" },
		["@markup.emphasis"] = { link = "TSEmphasis" },
		["@markup.environment"] = { link = "TSEnvironment" },
		["@markup.environment.name"] = { link = "TSEnvironmentName" },
		["@markup.heading"] = { link = "TSTitle" },
		["@markup.link"] = { link = "TSTextReference" },
		["@markup.link.label"] = { link = "TSStringSpecial" },
		["@markup.link.url"] = { link = "TSURI" },
		["@markup.list"] = { link = "TSPunctSpecial" },
		["@markup.list.checked"] = { link = "Green" },
		["@markup.list.unchecked"] = { link = "Ignore" },
		["@markup.math"] = { link = "TSMath" },
		["@markup.quote"] = { link = "Grey" },
		["@markup.raw"] = { link = "TSLiteral" },
		["@markup.strike"] = { link = "TSStrike" },
		["@markup.strong"] = { link = "TSStrong" },
		["@markup.underline"] = { link = "TSUnderline" },
		["@math"] = { link = "TSMath" },
		["@method"] = { link = "TSMethod" },
		["@method.call"] = { link = "TSMethodCall" },
		["@module"] = { link = "TSNamespace" },
		["@module.go"] = { link = "goTSNamespace" },
		["@namespace"] = { link = "TSNamespace" },
		["@namespace.go"] = { link = "goTSNamespace" },
		["@none"] = { link = "TSNone" },
		["@number"] = { link = "TSNumber" },
		["@number.float"] = { link = "TSFloat" },
		["@operator"] = { link = "TSOperator" },
		["@parameter"] = { link = "TSParameter" },
		["@parameter.reference"] = { link = "TSParameterReference" },
		["@preproc"] = { link = "TSPreProc" },
		["@property"] = { link = "TSProperty" },
		["@property.toml"] = { link = "tomlTSProperty" },
		["@punctuation.bracket"] = { link = "TSPunctBracket" },
		["@punctuation.bracket.regex"] = { link = "TSStringRegex" },
		["@punctuation.delimiter"] = { link = "TSPunctDelimiter" },
		["@punctuation.special"] = { link = "TSPunctSpecial" },
		["@repeat"] = { link = "TSRepeat" },
		["@storageclass"] = { link = "TSStorageClass" },
		["@storageclass.lifetime"] = { link = "TSStorageClassLifetime" },
		["@strike"] = { link = "TSStrike" },
		["@string"] = { link = "TSString" },
		["@string.escape"] = { link = "TSStringEscape" },
		["@string.escape.json"] = { link = "jsonTSStringEscape" },
		["@string.escape.yaml"] = { link = "yamlTSStringEscape" },
		["@string.json"] = { link = "jsonTSString" },
		["@string.regex"] = { link = "TSStringRegex" },
		["@string.regexp"] = { link = "TSStringRegex" },
		["@string.special"] = { link = "TSStringSpecial" },
		["@string.special.symbol"] = { link = "TSSymbol" },
		["@string.special.url"] = { link = "TSURI" },
		["@string.toml"] = { link = "tomlTSString" },
		["@string.yaml"] = { link = "yamlTSString" },
		["@symbol"] = { link = "TSSymbol" },
		["@tag"] = { link = "TSTag" },
		["@tag.attribute"] = { link = "TSTagAttribute" },
		["@tag.delimiter"] = { link = "TSTagDelimiter" },
		["@text"] = { link = "TSText" },
		["@text.danger"] = { link = "TSDanger" },
		["@text.diff.add"] = { link = "diffAdded" },
		["@text.diff.delete"] = { link = "diffRemoved" },
		["@text.emphasis"] = { link = "TSEmphasis" },
		["@text.environment"] = { link = "TSEnvironment" },
		["@text.environment.name"] = { link = "TSEnvironmentName" },
		["@text.gitcommit"] = { link = "TSNone" },
		["@text.html"] = { link = "htmlTSText" },
		["@text.literal"] = { link = "TSLiteral" },
		["@text.math"] = { link = "TSMath" },
		["@text.note"] = { link = "TSNote" },
		["@text.reference"] = { link = "TSTextReference" },
		["@text.strike"] = { link = "TSStrike" },
		["@text.strong"] = { link = "TSStrong" },
		["@text.title"] = { link = "TSTitle" },
		["@text.todo"] = { link = "TSTodo" },
		["@text.todo.checked"] = { link = "Green" },
		["@text.todo.unchecked"] = { link = "Ignore" },
		["@text.underline"] = { link = "TSUnderline" },
		["@text.uri"] = { link = "TSURI" },
		["@text.warning"] = { link = "TSWarning" },
		["@todo"] = { link = "TSTodo" },
		["@type"] = { link = "TSType" },
		["@type.builtin"] = { link = "TSTypeBuiltin" },
		["@type.definition"] = { link = "TSTypeDefinition" },
		["@type.qualifier"] = { link = "TSTypeQualifier" },
		["@uri"] = { link = "TSURI" },
		["@variable"] = { link = "TSVariable" },
		["@variable.builtin"] = { link = "TSVariableBuiltin" },
		["@variable.member"] = { link = "TSField" },
		["@variable.member.yaml"] = { link = "yamlTSField" },
		["@variable.parameter"] = { link = "TSParameter" },
		--]]

		-- LSP semantic tokens
		["@lsp.type.comment"] = { link = "@comment" },
		["@lsp.type.enum"] = { link = "@type" },
		["@lsp.type.interface"] = { link = "Identifier" },
		["@lsp.type.keyword"] = { link = "@keyword" },
		["@lsp.type.namespace"] = { link = "@namespace" },
		["@lsp.type.parameter"] = { link = "@parameter" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.variable"] = {}, -- use treesitter styles for regular variables
		["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.operator.injected"] = { link = "@operator" },
		["@lsp.typemod.string.injected"] = { link = "@string" },
		["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
		["@lsp.typemod.variable.injected"] = { link = "@variable" },

		--[[
		["@lsp.type.boolean"] = { link = "@boolean" },
		["@lsp.type.builtinConstant"] = { link = "@constant.builtin" },
		["@lsp.type.builtinType"] = { link = "@type.builtin" },
		["@lsp.type.class"] = { link = "@type" },
		["@lsp.type.comment"] = { link = "@comment" },
		["@lsp.type.decorator"] = { link = "@function" },
		["@lsp.type.derive"] = { link = "@constructor" },
		["@lsp.type.deriveHelper"] = { link = "@attribute" },
		["@lsp.type.enum"] = { link = "@type" },
		["@lsp.type.enumMember"] = { link = "@property" },
		["@lsp.type.escapeSequence"] = { link = "@string.escape" },
		["@lsp.type.formatSpecifier"] = { link = "@punctuation.special" },
		["@lsp.type.function"] = { link = "@function" },
		["@lsp.type.generic"] = { link = "@text" },
		["@lsp.type.interface"] = { link = "@type" },
		["@lsp.type.keyword"] = { link = "@keyword" },
		["@lsp.type.lifetime"] = { link = "@storageclass.lifetime" },
		["@lsp.type.macro"] = { link = "@constant.macro" },
		["@lsp.type.magicFunction"] = { link = "@function.builtin" },
		["@lsp.type.method"] = { link = "@method" },
		["@lsp.type.modifier"] = { link = "@type.qualifier" },
		["@lsp.type.namespace"] = { link = "@namespace" },
		["@lsp.type.namespace.go"] = { link = "@namespace.go" },
		["@lsp.type.number"] = { link = "@number" },
		["@lsp.type.operator"] = { link = "@operator" },
		["@lsp.type.parameter"] = { link = "@parameter" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.regexp"] = { link = "@string.regex" },
		["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
		["@lsp.type.selfTypeKeyword"] = { link = "@type" },
		["@lsp.type.string"] = { link = "@string" },
		["@lsp.type.struct"] = { link = "@type" },
		["@lsp.type.type"] = { link = "@type" },
		["@lsp.type.typeAlias"] = { link = "@type.definition" },
		["@lsp.type.typeParameter"] = { link = "@type.definition" },
		["@lsp.type.variable"] = { link = "@variable" },
		["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
		["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.function.readonly"] = { link = "@method" },
		["@lsp.typemod.keyword.async"] = { link = "@keyword" },
		["@lsp.typemod.keyword.injected"] = { link = "@keyword" },
		["@lsp.typemod.macro.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.method.readonly"] = { link = "@method" },
		["@lsp.typemod.operator.injected"] = { link = "@operator" },
		["@lsp.typemod.string.injected"] = { link = "@string" },
		["@lsp.typemod.struct.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.type.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.typeAlias.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.variable.callable"] = { link = "@function" },
		["@lsp.typemod.variable.constant.rust"] = { link = "@constant" },
		["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
		["@lsp.typemod.variable.defaultLibrary.go"] = { link = "@constant.builtin.go" },
		["@lsp.typemod.variable.defaultLibrary.javascript"] = { link = "@constant.builtin" },
		["@lsp.typemod.variable.defaultLibrary.javascriptreact"] = { link = "@constant.builtin" },
		["@lsp.typemod.variable.defaultLibrary.typescript"] = { link = "@constant.builtin" },
		["@lsp.typemod.variable.defaultLibrary.typescriptreact"] = { link = "@constant.builtin" },
		["@lsp.typemod.variable.injected"] = { link = "@variable" },
		["@lsp.typemod.variable.static"] = { link = "Red" },
		--]]

		-- telescope.nvim: https://github.com/nvim-telescope/telescope.nvim
		TelescopeBorder = { fg = p.bg_alt, bg = p.bg_alt },
		TelescopeNormal = { fg = p.fg, bg = p.bg_alt },
		TelescopeSelection = { fg = p.fg, bg = p.bg_urgent },
		TelescopeMatching = { fg = p.bg, bg = p.cyan },
		TelescopePromptNormal = { fg = p.fg, bg = p.bg_urgent },
		TelescopePromptTitle = { fg = p.cyan, bg = p.bg_urgent },
		TelescopePromptBorder = { fg = p.bg_urgent, bg = p.bg_urgent },
		TelescopePreviewTitle = { fg = p.fg_alt, bg = p.bg_alt },
		TelescopePreviewBorder = { fg = p.bg_alt, bg = p.bg_alt },
		TelescopeResultsTitle = { fg = p.fg_alt, bg = p.bg_alt },
		TelescopeResultsBorder = { fg = p.bg_alt, bg = p.bg_alt },

		-- hop.nvim
		HopNextKey = { fg = p.yellow },
		HopNextKey1 = { fg = p.orange },
		HopNextKey2 = { fg = p.red },
		HopUnmatched = { fg = p.fg_alt },
		HopCursor = { bg = p.fg },
		HopPreview = { fg = p.magenta }

	}

	vim.g.terminal_color_0 = p.bg
	vim.g.terminal_color_1 = p.red
	vim.g.terminal_color_2 = p.green
	vim.g.terminal_color_3 = p.yellow
	vim.g.terminal_color_4 = p.blue
	vim.g.terminal_color_5 = p.magenta
	vim.g.terminal_color_6 = p.cyan
	vim.g.terminal_color_7 = p.fg
	vim.g.terminal_color_8 = p.fg_alt
	vim.g.terminal_color_9 = p.red
	vim.g.terminal_color_10 = p.green
	vim.g.terminal_color_11 = p.yellow
	vim.g.terminal_color_12 = p.blue
	vim.g.terminal_color_13 = p.magenta
	vim.g.terminal_color_14 = p.cyan
	vim.g.terminal_color_15 = p.fg

	return theme
end

return T
