backend = "glx";
vsync = true;
use-damage = true;
unredir-if-possible = true;

animations = (
	{
		triggers = [ "open", "show" ];
		preset = "appear";
		scale = 0.5;
		duration = 0.15;
	},
	{
		triggers = [ "close", "hide" ];
		preset = "disappear";
		scale = 0.5;
		duration = 0.15;
	},
	{
		triggers = [ "geometry" ];
		preset = "geometry-change";
		duration = 0.3;
	}
)
