[colors.bright]
black = "#656565"
blue = "#3E7CE8"
cyan = "#35C6DB"
green = "#38C644"
magenta = "#944ACA"
red = "#EA4047"
white = "#DBDBDB"
yellow = "#F9C132"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#0F0F0F"
blue = "#3E7CE8"
cyan = "#35C6DB"
green = "#38C644"
magenta = "#944ACA"
red = "#EA4047"
white = "#DBDBDB"
yellow = "#F9C132"

[colors.primary]
background = "#0F0F0F"
foreground = "#DBDBDB"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
